build:
  image: cblomart/rpi-basebuild
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - make binary
    - ls -lah ./src/haproxy-*/haproxy
    - strip --strip-all ./src/haproxy-*/haproxy
    - ls -lah ./src/haproxy-*/haproxy
    - ldd  ./src/haproxy-*/haproxy
    - ./src/haproxy-*/haproxy -vv
    - make
publish:
  docker:
    username: cblomart
    password: $$DOCKERHUB_PASS
    email: cblomart@gmail.com
    repo: cblomart/rpi-haproxy
    insecure: true
    tag:
       - $$BRANCH
  bintray:
    username: cblomart
    password: $$DOCKERHUB_PASS
    branch: $$BRANCH
    artifacts:
      - file:  /usr/local/bin/
        owner: cblomart
        type: executable
        repository: files
        package: haproxy
        version: 1.6.5
        target: haproxy
        publish: true
        override: true
