build:
  image: cblomart/rpi-basebuild
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - make deps
    - make binary
    - ldd  ./src/haproxy-*/haproxy
    - ./src/haproxy-*/haproxy -vv
    - make
publish:
  docker:
    username: cblomart
    password: $$DOCKERHUB_PASS
    email: cblomart@gmail.com
    repo: cblomart/rpi-haproxy
    insecure: true
    tag:
       - $$BRANCH
       - latest

