build:
<<<<<<< HEAD
  image: cblomart/rpi-basebuild
=======
  image: cblomart/rpi-buildroot
>>>>>>> d4dec08344aa453c3f54758b2fdbea7845f99a45
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - make deps
    - make binary
    - ls -lah ./src/haproxy-*/haproxy
    - strip --strip-all ./src/haproxy-*/haproxy
    - make
publish:
  docker:
    username: cblomart
    password: $$DOCKERHUB_PASS
    email: cblomart@gmail.com
    repo: cblomart/rpi-haproxy
    insecure: true
    tag:
       - $$BRANCH
       - latest

