build:
  image: cblomart/rpi-basebuild
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - make 
    - docker build -t cblomart/rpi-haproxy .
publish:
  docker:
    username: cblomart
    password: $$DOCKERHUB_PASS
    email: cblomart@gmail.com
    repo: cblomart/rpi-haproxy
    insecure: true
    tag:
       - $$BRANCH
       - $$COMMIT
  bintray:
    username: cblomart
    password: $$DOCKERHUB_PASS
    branch: $$BRANCH
    artifacts:
      - file:  /usr/local/bin/
        owner: cblomart
        type: executable
        repository: files
        package: haproxy
        version: 1.6.5
        target: haproxy
        publish: true
        override: true
